import { JumboTheme } from '@jumbo/components';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import type { Metadata } from 'next';
import { Lexend } from 'next/font/google';
import { CONFIG } from './_config';
const lexend = Lexend({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'NextJS MUI and TypeScript Boilerplate',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={lexend.className}>
        <AppRouterCacheProvider>
          <JumboTheme init={CONFIG.THEME}>{children}</JumboTheme>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
