import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextJS MUI and TypeScript Boilerplate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
      </body>
    </html>
  );
}