import { JumboTheme } from '@jumbo/components';
import {
  JumboLayout,
  JumboLayoutProvider,
} from '@jumbo/components/JumboLayout';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import type { Metadata } from 'next';
import { Lexend } from 'next/font/google';
import { Footer, Header } from './_components/layout';
import { CONFIG } from './_config';
import { defaultLayoutConfig } from './_config/layouts';

const lexend = Lexend({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'NextJS MUI and TypeScript Boilerplate',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={lexend.className}>
        <AppRouterCacheProvider>
          <JumboTheme init={CONFIG.THEME}>
            <JumboLayoutProvider layoutConfig={defaultLayoutConfig}>
              <JumboLayout
                header={<Header />}
                footer={<Footer/>}
                sidebar={<div>me sidebar</div>}
              >
                {children}
              </JumboLayout>
            </JumboLayoutProvider>
          </JumboTheme>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
