import { JumboTheme } from '@jumbo/components';
import {
  JumboLayout,
  JumboLayoutProvider,
} from '@jumbo/components/JumboLayout';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import type { Metadata } from 'next';
import { Params } from 'next/dist/shared/lib/router/utils/route-matcher';
import { Lexend } from 'next/font/google';
import { Header } from '../_components/layout';
import { Sidebar } from '../_components/layout/Sidebar';
import { CONFIG } from '../_config';
import { defaultLayoutConfig } from '../_config/layouts';
import '../_utilities/style/scrollbar.css';

const lexend = Lexend({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'NextJS MUI and TypeScript Boilerplate',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: Params;
}) {
  return (
    <html lang={locale}>
      <body className={lexend.className}>
        <AppRouterCacheProvider>
          <JumboTheme init={CONFIG.THEME}>
            <JumboLayoutProvider layoutConfig={defaultLayoutConfig}>
              <JumboLayout
                header={<Header />}
                footer={<div>me footer</div>}
                sidebar={<Sidebar />}
              >
                {children}
              </JumboLayout>
            </JumboLayoutProvider>
          </JumboTheme>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
